# contribution.yaml
name: ðŸŽ Submit Content
description: Submit a character, custom code, or lorebook
title: "[Contribution] "
labels: ["contribution"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to our repository! Please fill out the information below carefully.
        
        Before proceeding, make sure you have read our [Contribution Guidelines](/documentation/contributing.md).
  
  # Basic Information
  - type: input
    id: content-name
    attributes:
      label: Content Name
      description: Name for your character, lorebook, etc
    validations:
      required: true
  
  - type: input
    id: description
    attributes:
      label: Short Description
      description: A brief description of your content (max 150 characters)
    validations:
      required: true
  
  - type: input
    id: author
    attributes:
      label: Author Name
      description: Your preferred attribution name. If left empty, will be used your github username. If unavailable, will fallback to 'Anonymous'
    validations:
      required: true
  
  - type: dropdown
    id: content-type
    attributes:
      label: Content Type
      options:
        - Character
        - Custom Code
        - Lorebook
    validations:
      required: true
  
  # Content Type Specific Fields
  - type: input
    id: image-url
    attributes:
      label: Image URL for your content
      description: Host your image [here](https://perchance.org/upload). Image is required for character submissions.
  
  - type: input
    id: perchance-url
    attributes:
      label: Perchance Character Share Link
      description: For character submissions only. See [here](/documentation/contributing.md) how to get the link.
  
  - type: textarea
    id: custom-code
    attributes:
      label: Custom Code
      description: For isolated custom code submissions only.
      render: javascript
  
  - type: textarea
    id: lorebook
    attributes:
      label: Lorebook Content
      description: For lorebook submissions only. Each sentence separated by double line breaks.
      render: plain
      placeholder: |
        First sentence
        
        Second sentence
        
        Third sentence
  
  - type: textarea
    id: readme
    attributes:
      label: README Content
      description: Description and documentation for your submission
    validations:
      required: true

  # Categories Section
  - type: markdown
    attributes:
      value: |
        ## Content Categories
        
        The following categories help users find your content. 
        While most are **optional**, proper categorization is **highly recommended**, because it helps users search and find your content.  
          
        > **Note:** Some tags are only valid for NSFW content and will be filtered accordingly.
        _Missing a category or tag? You can request new ones [here](../../issues/new?labels=category-request)._
  
  - type: dropdown
    id: rating
    attributes:
      label: Content Rating (REQUIRED)
      description: This will determine content visibility and available tags
      options:
        - SFW
        - NSFW
    validations:
      required: true
      
  # This section will be automatically updated based on categories.json
  # BEGIN_CATEGORIES
  - type: dropdown
    id: species
    attributes:
      label: Species
      description: Character's species or race
      multiple: true
      options:
        - AI
        - Alien
        - Android
        - Angel
        - Beast
        - Canine
        - Centaur
        - Chimera
        - Clone
        - Cyborg
        - Deity
        - Demon
        - Dragon
        - Dwarf
        - Elemental
        - Elf
        - Fairy
        - Furry
        - Ghost
        - Golem
        - Half-breed
        - Harpy
        - Human
        - Incubus
        - Insect
        - Kitsune
        - Mermaid
        - Monster Girl/Boy
        - Mythological
        - Neko
        - Orc
        - Robot
        - Scaly
        - Shapeshifter
        - Slime
        - Spirit
        - Succubus
        - Tentacle Monster
        - Unspecified
        - Vampire
        - Werewolf
        - Zombie / Undead
    validations:
      required: false

  - type: dropdown
    id: gender
    attributes:
      label: Gender
      description: Character's gender identity
      multiple: true
      options:
        - Agender
        - Androgynous
        - Bigender
        - Female
        - Futanari
        - Gender Bender
        - Gender Non-Conforming
        - Gender Transformation
        - Genderfluid
        - Male
        - Non-binary
        - Questioning
        - Transgender
    validations:
      required: false

  - type: dropdown
    id: age group
    attributes:
      label: Age Group
      description: Character's age category
      multiple: true
      options:
        - Adult
        - Ageless
        - Ancient
        - Child
        - Elder
        - Immortal
        - Middle-aged
        - Teen
        - Young Adult
    validations:
      required: false

  - type: dropdown
    id: genre
    attributes:
      label: Genre
      description: Story type or style
      multiple: true
      options:
        - Action
        - Adult Drama
        - Adventure
        - Comedy
        - Crime
        - Cyberpunk
        - Dark Romance
        - Drama
        - Educational
        - Erotic
        - Fantasy
        - Fetish
        - Friendship
        - Gothic
        - Historical
        - Horror
        - Military
        - Musical
        - Mystery
        - Political
        - Post-apocalyptic
        - Psychological
        - RPG
        - Romance
        - School Life
        - Sci-Fi
        - Sexual Roleplay
        - Slice of Life
        - Space Opera
        - Sports
        - Steampunk
        - Supernatural
        - Thriller
        - Urban Fantasy
        - Western
    validations:
      required: false

  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Source of inspiration
      multiple: true
      options:
        - Adult Comics
        - Adult Film
        - Adult Game
        - Adult Literature
        - Anime
        - Art
        - Book
        - Celebrity
        - Comic
        - Content Creator
        - Doujinshi
        - Fanfiction
        - Folk Tale
        - Game
        - Hentai
        - Historical
        - Legend
        - Light Novel
        - Manga
        - Movie
        - Music
        - Mythology
        - Only fans
        - Original
        - Perchance
        - Podcast
        - Poetry
        - Pornstar
        - Real life
        - TV Show
        - Visual Novel
        - Web Series
    validations:
      required: false

  - type: dropdown
    id: role
    attributes:
      label: Role
      description: Character's primary role or occupation
      multiple: true
      options:
        - Adult Entertainer
        - Adventurer
        - Artist
        - Assassin
        - Assistant
        - Athlete
        - Best friend
        - Celebrity
        - Chef
        - Deity
        - Detective
        - Doctor
        - Dominatrix/Dom
        - Engineer
        - Escort
        - Explorer
        - Farmer
        - Friend
        - Guard
        - Healer
        - Hero
        - Idol
        - Knight
        - LI (Love Interest)
        - Leader
        - Mage
        - Merchant
        - Musician
        - Noble
        - Pet
        - Pilot
        - Priest/Priestess
        - Professional
        - Programmer
        - Researcher
        - Rival
        - Royalty
        - Scientist
        - Servant
        - Sex Worker
        - Soldier
        - Student
        - Teacher
        - Thief
        - Utility
        - Villain
        - Warrior
        - Writer
    validations:
      required: false

  - type: dropdown
    id: personality
    attributes:
      label: Personality
      description: Character's primary personality traits
      multiple: true
      options:
        - Abusive / Toxic
        - Affectionate
        - Aggressive
        - Ambitious
        - Analytical
        - Artistic
        - Brave
        - Caring
        - Cheerful
        - Cold
        - Confident
        - Cowardly
        - Deceptive
        - Dominant
        - Dramatic
        - Energetic
        - Forgiving
        - Friendly
        - Honest
        - Humble
        - Impulsive
        - Intelligent
        - Judgmental
        - Lazy
        - Loyal
        - Lustful
        - Manipulative
        - Masochistic
        - Mysterious
        - Naive
        - Obsessive
        - Patient
        - Playful
        - Possessive
        - Progressive
        - Protective
        - Proud
        - Rebellious
        - Reserved
        - Sadistic
        - Sarcastic
        - Seductive
        - Serious
        - Shy
        - Submissive
        - Teasing
        - Traditional
        - Vengeful
        - Violent
        - Wise
    validations:
      required: false

  - type: dropdown
    id: physical traits
    attributes:
      label: Physical Traits
      description: Notable physical characteristics
      multiple: true
      options:
        - Androgynous Look
        - Athletic
        - Endowed
        - Glasses
        - Heterochromia
        - Horns
        - Long Hair
        - Multiple Arms
        - Multiple Eyes
        - Muscular
        - Petite
        - Plus-sized
        - Pointed Ears
        - Scarred
        - Short
        - Short Hair
        - Slim
        - Tail
        - Tall
        - Tattooed
        - Unusual Hair Color
        - Voluptuous
        - Wings
    validations:
      required: false

  - type: dropdown
    id: fetishes
    attributes:
      label: Fetishes
      description: Adult-themed interests
      multiple: true
      options:
        - BDSM
        - Body Modification
        - Bondage
        - Breeding
        - Cross-dressing
        - Exhibition
        - Feet
        - Food Play
        - Furry
        - Harem
        - Hypnosis
        - Latex
        - Leather
        - Macro/Micro
        - Master/Slave
        - Medical
        - Mind Control
        - Monster
        - Orgasm Control
        - Pet Play
        - Pregnancy
        - Roleplay
        - Sensory Deprivation
        - Size Difference
        - Slavery
        - Temperature Play
        - Tentacles
        - Transformation
        - Uniform
        - Vore
        - Voyeurism
    validations:
      required: false

  - type: dropdown
    id: sexual content
    attributes:
      label: Sexual Content
      description: Sexual activities and preferences
      multiple: true
      options:
        - Anal
        - Bukkake
        - Creampie
        - Deep Throat
        - Double Penetration
        - Edging
        - Face-sitting
        - Fingering
        - First Time
        - Fisting
        - Gangbang
        - Gentle
        - Group
        - Marathon
        - Masturbation
        - Multiple Partners
        - Mutual
        - Non-virgin
        - One-sided
        - Oral
        - Public
        - Quickie
        - Rimming
        - Rough
        - Semi-public
        - Squirting
        - Threesome
        - Toys
        - Vanilla
        - Virgin
    validations:
      required: false

  - type: dropdown
    id: sexual preferences
    attributes:
      label: Sexual Preferences
      description: Sexual orientation and relationship preferences
      multiple: true
      options:
        - Asexual
        - Bisexual
        - Casual
        - Committed
        - Demisexual
        - Experimental
        - Friends with Benefits
        - Gay
        - Lesbian
        - No Strings Attached
        - Open Relationship
        - Pansexual
        - Polyamorous
        - Straight
    validations:
      required: false

  - type: dropdown
    id: sexual experience
    attributes:
      label: Sexual Experience
      description: Character's sexual experience level
      multiple: true
      options:
        - Curious
        - Experienced
        - Experimenting
        - Expert
        - Inexperienced
        - Promiscuous
        - Reserved
        - Somewhat Experienced
        - Very Experienced
        - Virgin
    validations:
      required: false

  - type: dropdown
    id: setting
    attributes:
      label: Setting
      description: Primary environment or world setting
      multiple: true
      options:
        - Adult Club
        - Alternate History
        - Ancient
        - Brothel
        - Castle
        - Contemporary
        - Cyberpunk
        - Dream World
        - Dungeon
        - Fantasy World
        - Future
        - Harem
        - Medieval
        - Military Base
        - Modern
        - Parallel Universe
        - Post-Apocalyptic
        - Prehistoric
        - Rural
        - School
        - Space
        - Steampunk
        - Underground
        - Urban
        - Victorian
        - Virtual Reality
        - Wilderness
    validations:
      required: false
  # END_CATEGORIES

  # Legal Section
  - type: markdown
    attributes:
      value: |
        ## Legal Confirmations
        
        Please carefully read and confirm the following statements:
  
  - type: checkboxes
    id: legal-confirmations
    attributes:
      label: Legal Confirmations
      options:
        - label: I confirm that this content does not violate any laws, repository rules, or policies, including but not limited to copyright, intellectual property rights, and content guidelines.
          required: true
        - label: I agree to release this content under the MIT License, granting permission for others to use, modify, and distribute it under the same terms as the repository.
          required: true
        - label: I understand that if this content is found to violate any laws or policies, it may be removed without prior notice, and I may be held legally responsible for any violations.
          required: true
