name: 🚨 Report Content
description: Report content that violates the rules or laws
labels: ["illegal-content", "report"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us identify and review the reported illegal content.
  - type: textarea
    id: content_link
    attributes:
      label: Provide the link to the reported content
      placeholder: Enter the URL or direct reference to the content being reported
    validations:
      required: true
  - type: checkboxes
    id: content_type
    attributes:
      label: Select the type of content being reported
      options:
        - "Character"
        - "Lorebook"
        - "Perchance Content"
        - "Other (Please specify)"
  - type: checkboxes
    id: illegal_reason
    attributes:
      label: Select the reason for reporting the content
      options:
        - "Child Exploitation"
        - "Intellectual Property Infringement"
        - "Piracy/Unauthorized Sharing"
        - "Fraudulent Activity"
        - "Hacking/Unauthorized Access"
        - "Hate Speech or Incitement to Violence"
        - "Other (Please describe)"
  - type: textarea
    id: description
    attributes:
      label: Provide a detailed description of why this content is considered illegal
      placeholder: Explain the situation in detail, providing evidence or context
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information (Optional)
      placeholder: Any other relevant information that might help in the review process
  - type: textarea
    id: contact_info
    attributes:
      label: Contact information (Optional)
      placeholder: Provide an email or method to reach you for follow-up
  - type: markdown
    attributes:
      value: |
        By submitting this report, I confirm that the information provided is accurate to the best of my knowledge. Any false or misleading reports may result in actions against my account.
  - type: dropdown
    id: submit_confirmation
    attributes:
      label: "Do you agree to the above terms?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue. We will review your submission and get back to you as soon as possible.
