name: 🚨 Report Content
description: Report content that violates the rules or laws
title: "[Report] "
labels: ["report"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us identify and review the reported illegal content.
  - type: input
    id: content_link
    attributes:
      label: Provide the link to the reported content
      placeholder: Enter the URL or direct reference to the content being reported
    validations:
      required: true
  - type: dropdown
    id: content_type
    attributes:
      label: Select the type of content being reported
      options:
        - label: "Character"
        - label: "Lorebook"
        - label: "Perchance Content"
        - label: "Other (Please specify)"
  - type: input
    id: other_content_type
    attributes:
      label: "Specify the content type"
      placeholder: Enter a description if you selected 'Other'
    validations:
      required: false
  - type: checkboxes
    id: illegal_reason
    attributes:
      label: Select the reason for reporting the content
      options:
        - label: "Child Exploitation"
        - label: "Intellectual Property Infringement"
        - label: "Piracy/Unauthorized Sharing"
        - label: "Fraudulent Activity"
        - label: "Hacking/Unauthorized Access"
        - label: "Hate Speech or Incitement to Violence"
        - label: "Other (Please describe)"
  - type: textarea
    id: description
    attributes:
      label: Provide a description of why this content is considered illegal
      placeholder: |
        Describe the issue and provide details on which laws (including country-specific laws) or rules are being violated.
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information (Optional)
      placeholder: Any other relevant information that might help in the review process
  - type: checkboxes
    id: submit_confirmation
    attributes:
      label: "I confirm that the information provided is accurate to the best of my knowledge."
      options:
        - label: "I agree"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue. We will review your submission and get back to you as soon as possible.

