# .github/workflows/update-categories-on-issue-template.yml
name: Update Categories in Templates

on:
  push:
    paths:
      - 'categories.json'
    branches:
      - develop
      - main
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Debug File Presence
        run: ls -l categories.json

      - name: Debug Directory Structure
        run: ls -R .github/ISSUE_TEMPLATE/

      - name: Debug Scripts Directory
        run: ls -l .github/scripts/

      - name: Debug File Permissions
        run: ls -l .github/ISSUE_TEMPLATE/

      - name: Debug Python Environment
        run: python --version && which python
        
      
      - name: Update Templates
        id: update-templates
        run: |
          python .github/scripts/update_categories_on_templates.py

      
      - name: Check for Changes
        id: check-changes
        run: |
          if git diff --exit-code .github/ISSUE_TEMPLATE/; then
            echo "No changes detected in templates"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in templates"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          commit-message: "chore: update categories in issue templates"
          title: "[Automatic Action] Update categories in issue templates"
          body: |
            Automatically updated categories in the issue templates based on changes to categories.json
            
            Updates include:
            - Contribution template
            - Category request template
          branch: "auto-update/categories-templates"
          delete-branch: true
          base: ${{ github.ref_name }}

      - name: Check PR Creation
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          if [ -z "${{ steps.create-pr.outputs.pull-request-number }}" ]; then
            echo "Failed to create Pull Request"
            exit 1
          fi
          echo "Successfully created PR #${{ steps.create-pr.outputs.pull-request-number }}"
